---
- hosts: all
  become: yes

  tasks:
    - name: install Linux headers
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - linux-headers-generic
          - linux-headers-raspi

    - name: install build-essential
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - build-essential

    - name: install dkms
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - dkms

    - name: enable passwordless sudo
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/sudoers.d/florin

    - name: configure networking
      template: src=templates/{{ item }}.server dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/netplan/99_config.yaml
    
    - name: configure hostname
      shell: hostnamectl hostname server.{{ local_domain }}
    
    - name: disable cloud-init
      file: path=/etc/cloud/cloud-init.disabled state=touch

    - name: remove cloud-init network config
      file: path=/etc/netplan/50-cloud-init.yaml state=absent

    - name: apply netplan configuration
      shell: netplan apply

    - name: make sure the RTC battery is being charged
      lineinfile:
        path: /boot/firmware/config.txt
        line: "dtparam=rtc_bbat_vchg=3000000"
        state: present
        insertafter: EOF
