---
- hosts: all
  become: yes

  tasks:
    - name: install kernel module build dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - linux-headers-generic
          - build-essential
          - dkms

    - name: enable passwordless sudo
      template: src=templates/etc/sudoers.d/user dest=/etc/sudoers.d/{{ main_user }} owner=root group=root mode=0644

    - name: configure networking
      template: src=templates/{{ item }}.server dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/netplan/99_config.yaml
    
    - name: configure hostname
      shell: hostnamectl hostname server-new.{{ local_domain }}
    
    - name: disable cloud-init
      file: path=/etc/cloud/cloud-init.disabled state=touch

    - name: remove cloud-init network config
      file: path=/etc/netplan/50-cloud-init.yaml state=absent

    - name: apply netplan configuration
      shell: netplan apply
