---
- hosts: 127.0.0.1
  become: yes

  pre_tasks:
    - name: enable passwordless sudo
      template: src=templates/etc/sudoers.d/user dest=/etc/sudoers.d/{{ main_user }} owner=root group=root mode=0644

    - name: configure networking
      template: src=templates/{{ item }}.gateway dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/netplan/00-installer-config.yaml

    - name: configure hostname
      shell: hostnamectl hostname gateway.{{ local_domain }}

    - name: disable cloud-init
      file: path=/etc/cloud/cloud-init.disabled state=touch

    - name: apply netplan configuration
      shell: netplan apply

  roles:
    - role: unbound
      tags: unbound
