---
- hosts: all
  become: yes


  handlers:
  - name: restart chrony
    service:
      name: chrony
      state: restarted

  - name: restart unbound
    service:
      name: unbound
      state: restarted

  - name: restart isc-dhcp-server
    service:
      name: isc-dhcp-server
      state: restarted

  - name: restart nftables
    service:
      name: nftables
      state: restarted

  - name: restart ssh
    service:
      name: ssh
      state: restarted

  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted

  - name: restart wireguard
    service:
      name: wg-quick@wg0
      state: restarted

  - name: restart smbd
    service:
      name: smbd
      state: restarted

  - name: restart nmbd
    service:
      name: nmbd
      state: restarted

  - name: restart wsdd-server
    service:
      name: wsdd-server
      state: restarted

  tasks:
    - name: enable ip forwarding
      sysctl: name=net.ipv4.ip_forward value=1 sysctl_file=/etc/sysctl.d/20-ip-forward.conf sysctl_set=yes

    - name: install various packages and update apt cache
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - vim
          - net-tools
          - mc
          - nmap
          - iotop
          - iftop
          - stress-ng
          - lm-sensors
          - bind9-dnsutils
          - bind9-host
          - qrencode
          - dos2unix
          - apt-transport-https

    - name: configure various packages
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/htoprc

    - name: install various scripts
      copy:
        src: templates/{{ item }}
        dest: /{{ item }}
        owner: root
        group: root
        mode: 0755
      with_items:
        - usr/local/bin/battery.sh

    - name: configure nftables
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0755
      with_items:
        - etc/nftables.conf
      notify: restart nftables

    - name: enable nftables
      service:
        name: nftables
        enabled: yes
        state: started

    - name: install wireguard
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - wireguard
          - wireguard-tools

    - name: configure wireguard
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0600
      with_items:
        - etc/wireguard/wg0.conf
        - etc/wireguard/README.md
      notify: restart wireguard

    - name: enable wireguard
      service:
        name: wg-quick@wg0
        enabled: yes
        state: started

    - name: create wireguard clients directory
      file:
        path: /etc/wireguard/clients
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: loop through the wireguard_clients variable and create a file in /etc/wireguard/clients/ for each client
      template:
        src: templates/etc/wireguard/client.conf
        dest: /etc/wireguard/clients/{{ client.name }}.conf
        owner: root
        group: root
        mode: '0600'
      loop: "{{ wireguard_clients }}"
      loop_control:
        loop_var: client

    - name: configure ssh
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/ssh/sshd_config.d/99-home.conf
        - etc/ssh/banner.txt
      notify: restart ssh

    - name: full Unbound configuration (re-applies and then extends minimal configuration from init-gateway.yml)
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/unbound/unbound.conf.d/10-resolver.conf
        - etc/unbound/named.cache
        - etc/unbound/unbound.conf.d/20-nameserver.conf
        - etc/unbound/home.local
        - etc/unbound/home.local.reverse
        - etc/unbound/README.md
      notify: restart unbound
      tags: unbound
    
    - name: touch Unbound log file
      file: path=/var/log/unbound.log state=touch owner=syslog group=adm mode=0640
      changed_when: false
      tags: unbound

    - name: configure Unbound logging
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/rsyslog.d/10-unbound.conf
        - etc/logrotate.d/unbound
      notify: restart rsyslog
      tags: unbound

    - name: install DHCP server
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - isc-dhcp-server
      tags: dhcp

    - name: enable isc-dhcp-server
      service:
        name: isc-dhcp-server
        enabled: yes
        state: started
      tags: dhcp

    - name: disable isc-dhcp-server6
      service:
        name: isc-dhcp-server6
        enabled: no
        state: stopped
      tags: dhcp

    - name: configure DHCP server
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/dhcp/dhcpd.conf
      notify: restart isc-dhcp-server
      tags: dhcp

    - name: touch DHCP server log file
      file: path=/var/log/dhcpd.log state=touch owner=syslog group=adm mode=0640
      changed_when: false
      tags: dhcp

    - name: configure DHCP server logging
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/rsyslog.d/10-dhcpd.conf
        - etc/logrotate.d/dhcpd
      notify: restart rsyslog
      tags: dhcp

    - name: install chrony (also uninstalls systemd-timesyncd)
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - chrony

    - name: make sure chrony is enabled and running
      service:
        name: chrony
        enabled: yes
        state: started

    - name: configure chrony
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/chrony/conf.d/allow.conf
      notify: restart chrony

    - name: install Samba
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - samba
          - wsdd
          - wsdd-server
      tags: samba

    - name: make sure Samba services are enabled and running
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - smbd
        - nmbd
        - wsdd-server
      tags: samba

    - name: configure Samba
      template: src=templates/etc/samba/smb.conf.gateway dest=/etc/samba/smb.conf owner=root group=root mode=0644
      notify:
        - restart smbd
        - restart nmbd
        - restart wsdd-server
      tags: samba

    - name: create rc.local script
      template: src=templates/etc/rc.local-gateway dest=/etc/rc.local owner=root group=root mode=0755
      tags: rc.local

    - name: enable the rc-local service
      service:
        name: rc-local
        enabled: yes
      tags: rc.local
