---
- hosts: all
  become: yes


  handlers:
  - name: restart chrony
    service:
      name: chrony
      state: restarted

  - name: restart unbound
    service:
      name: unbound
      state: restarted

  - name: restart isc-dhcp-server
    service:
      name: isc-dhcp-server
      state: restarted

  - name: restart nftables
    service:
      name: nftables
      state: restarted

  - name: restart ssh
    service:
      name: ssh
      state: restarted

  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted


  tasks:
    - name: enable ip forwarding
      sysctl: name=net.ipv4.ip_forward value=1 sysctl_file=/etc/sysctl.d/20-ip-forward.conf sysctl_set=yes

    - name: install various packages and update apt cache
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - vim
          - net-tools
          - mc
          - nmap
          - iotop
          - iftop
          - stress-ng
          - lm-sensors
          - bind9-dnsutils
          - bind9-host

    - name: configure nftables
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0755
      with_items:
        - etc/nftables.conf
      notify: restart nftables

    - name: enable nftables
      service:
        name: nftables
        enabled: yes
        state: started

    - name: configure ssh
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/ssh/sshd_config.d/99-home.conf
        - etc/ssh/banner.txt
      notify: restart ssh

    - name: full Unbound configuration (re-applies and then extends minimal configuration from init-gateway.yml)
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/unbound/unbound.conf.d/10-resolver.conf
        - etc/unbound/named.cache
        - etc/unbound/unbound.conf.d/20-nameserver.conf
        - etc/unbound/home.local
        - etc/unbound/home.local.reverse
        - etc/unbound/db.rpz
      notify: restart unbound
    
    - name: touch Unbound log file
      file: path=/var/log/unbound.log state=touch owner=syslog group=adm mode=0640
      changed_when: false

    - name: configure Unbound logging
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/rsyslog.d/10-unbound.conf
        - etc/logrotate.d/unbound
      notify: restart rsyslog

    - name: install DHCP server
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - isc-dhcp-server

    - name: enable isc-dhcp-server
      service:
        name: isc-dhcp-server
        enabled: yes
        state: started

    - name: disable isc-dhcp-server6
      service:
        name: isc-dhcp-server6
        enabled: no
        state: stopped

    - name: configure DHCP server
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/dhcp/dhcpd.conf
      notify: restart isc-dhcp-server

    - name: install chrony (also uninstalls systemd-timesyncd)
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - chrony

    - name: make sure chrony is enabled and running
      service:
        name: chrony
        enabled: yes
        state: started

    - name: configure chrony
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/chrony/conf.d/allow.conf
      notify: restart chrony

    - name: install wireguard
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - wireguard
          - wireguard-tools
