---
- hosts: all
  become: yes


  handlers:
  - name: restart chrony
    service:
      name: chrony
      state: restarted

  - name: restart bind9
    service:
      name: bind9
      state: restarted

  - name: restart isc-dhcp-server
    service:
      name: isc-dhcp-server
      state: restarted


  tasks:
    - name: enable ip forwarding
      sysctl: name=net.ipv4.ip_forward value=1 sysctl_file=/etc/sysctl.d/20-ip-forward.conf sysctl_set=yes

    - name: install various packages and update apt cache
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - vim
          - net-tools
          - mc
          - nmap
          - iotop
          - iftop
          - stress-ng

    - name: enable nftables
      service:
        name: nftables
        enabled: yes
        state: started

    - name: full Bind9 configuration (re-applies and then extends minimal configuration from init-gateway.yml)
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/bind/named.conf.options
        - etc/default/named
        - etc/bind/named.conf.local
        - etc/bind/db.rpz
        - etc/bind/home.local
        - etc/bind/home.local.reverse
      notify: restart bind9

    - name: install DHCP server
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - isc-dhcp-server

    - name: disable isc-dhcp-server (change this to enable after the migration)
      service:
        name: isc-dhcp-server
        enabled: no
        state: stopped

    - name: disable isc-dhcp-server6
      service:
        name: isc-dhcp-server6
        enabled: no
        state: stopped

    - name: configure DHCP server
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/dhcp/dhcpd.conf
      # notify: restart isc-dhcp-server

    - name: install chrony (also uninstalls systemd-timesyncd)
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - chrony

    - name: make sure chrony is enabled and running
      service:
        name: chrony
        enabled: yes
        state: started

    - name: configure chrony
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/chrony/conf.d/allow.conf
      notify: restart chrony
