---
- hosts: gateway
  become: yes


  handlers:
  - name: restart nftables
    service:
      name: nftables
      state: restarted

  - name: restart ssh
    service:
      name: ssh
      state: restarted

  pre_tasks:
    - name: enable ip forwarding
      sysctl: name=net.ipv4.ip_forward value=1 sysctl_file=/etc/sysctl.d/20-ip-forward.conf sysctl_set=yes
      tags: ip_forwarding

    - name: install various packages and update apt cache
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - vim
          - net-tools
          - mc
          - nmap
          - iotop
          - iftop
          - stress-ng
          - lm-sensors
          - bind9-dnsutils
          - bind9-host
          - qrencode
          - dos2unix
          - apt-transport-https
          - gnupg

    - name: configure various packages
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/htoprc

#    - name: install various scripts
#      copy:
#        src: templates/{{ item }}
#        dest: /{{ item }}
#        owner: root
#        group: root
#        mode: 0755
#      with_items:
#        - usr/local/bin/battery.sh

    - name: configure ssh
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/ssh/sshd_config.d/99-home.conf
        - etc/ssh/banner.txt
      notify: restart ssh

#    - name: configure nftables
#      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0755
#      with_items:
#        - etc/nftables.conf
#      notify: restart nftables

#    - name: enable nftables
#      service:
#        name: nftables
#        enabled: yes
#        state: started

  roles:
  - role: unbound
    tags: unbound

  - role: wireguard
    tags: wireguard

  - role: chrony
    vars:
      chrony_mode: 'ntp_server'
    tags: chrony

#   - role: dhcp
#     tags: dhcp

#   - role: samba
#     vars:
#       samba_mode: 'gateway'
#     tags: samba

  - role: prometheus.prometheus.node_exporter
    tags: node_exporter
