---
- hosts: all
  become: yes

  handlers:
  - name: restart smbd
    service:
      name: smbd
      state: restarted

  - name: restart nmbd
    service:
      name: nmbd
      state: restarted

  - name: restart wsdd-server
    service:
      name: wsdd-server
      state: restarted

  - name: restart apache2
    service:
      name: apache2
      state: restarted

  - name: restart nginx
    service:
      name: nginx
      state: restarted

  pre_tasks:
    - name: install various packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - vim
          - net-tools
          - mc
          - nmap
          - iotop
          - iftop
          - stress-ng
          - lm-sensors
          - bind9-dnsutils
          - bind9-host
          - dos2unix
          - apt-transport-https
          - gnupg

    - name: configure various packages
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/htoprc

  roles:
  - role: chrony
    vars:
      chrony_mode: 'ntp_client'
    tags: chrony

  - role: dovecot
    tags: dovecot
  
  - role: postfix
    tags: postfix

  - role: docker
    tags: docker

  post_tasks:
    - name: install Samba
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - samba
          - wsdd
          - wsdd-server
      tags: samba

    - name: make sure Samba services are enabled and running
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - smbd
        - nmbd
        - wsdd-server
      tags: samba

    - name: create media directory for Samba
      file:
        path: /storage/media
        state: directory
        owner: "{{ main_user }}"
        group: "{{ main_user }}"
        mode: '0775'
      tags: samba

    - name: configure Samba
      template: src=templates/etc/samba/smb.conf.server dest=/etc/samba/smb.conf owner=root group=root mode=0644
      notify:
        - restart smbd
        - restart nmbd
        - restart wsdd-server
      tags: samba

    - name: install Apache
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apache2
      tags: apache

    - name: make sure Apache services are enabled and running
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - apache2
      tags: apache

    - name: remove 000-default.conf
      file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
      tags: apache

    - name: configure Apache
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/apache2/ports.conf
        - etc/apache2/sites-enabled/000-default-custom.conf
        - var/www/html/favicon.ico
      notify: restart apache2
      tags: apache

    - name: install Nginx
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nginx
      tags: nginx

    - name: make sure Nginx services are enabled and running
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - nginx
      tags: nginx

    - name: remove default from sites-enabled
      file: path=/etc/nginx/sites-enabled/default state=absent
      tags: nginx

    - name: configure Nginx
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/nginx/conf.d/0-log-format.conf
        - etc/nginx/conf.d/default.conf
      notify: restart nginx
      tags: nginx
