---
- hosts: all
  become: yes

  handlers:
  - name: restart chrony
    service:
      name: chrony
      state: restarted

  tasks:
    - name: install various packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - vim
          - net-tools
          - mc
          - nmap
          - iotop
          - iftop
          - stress-ng
          - lm-sensors

    - name: install chrony (also uninstalls systemd-timesyncd)
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - chrony

    - name: make sure chrony is enabled and running
      service:
        name: chrony
        enabled: yes
        state: started

    - name: configure chrony
      template: src=templates/{{ item }} dest=/{{ item }} owner=root group=root mode=0644
      with_items:
        - etc/chrony/sources.d/local-ntp-server.sources
        - etc/chrony/chrony.conf
      notify: restart chrony
