---
- name: install Nginx
  apt:
    name: nginx
    state: present
  register: nginx_install

- name: disable default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: deploy reverse proxy config
  template:
    src: "etc/nginx/sites-enabled/{{ nginx_reverse_proxy_config }}.conf.j2"
    dest: "/etc/nginx/sites-enabled/{{ nginx_reverse_proxy_config }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: make sure Nginx is enabled and running
  service:
    name: nginx
    enabled: yes
    state: started
  when: not (ansible_check_mode and nginx_install is changed)
