---
- name: install wireguard
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - wireguard
      - wireguard-tools
  register: wireguard_install

- name: configure wireguard
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - etc/wireguard/wg0.conf
    - etc/wireguard/README.md
  notify: restart wireguard

- name: enable wireguard
  service:
    name: wg-quick@wg0
    enabled: yes
    state: started
  when: not (ansible_check_mode and wireguard_install is changed)

- name: create wireguard clients directory
  file:
    path: /etc/wireguard/clients
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: loop through the wireguard_clients variable and create a file in /etc/wireguard/clients/ for each client
  template:
    src: etc/wireguard/client.conf
    dest: /etc/wireguard/clients/{{ client.name }}.conf
    owner: root
    group: root
    mode: '0600'
  loop: "{{ wireguard_clients }}"
  loop_control:
    loop_var: client
